### ISSUE TITLE
Foreign

### ISSUE THREAD

**Issue by nano996** [just-a-rookie-2001/Photovoltaic-System-Designer#1]
Hi Dear,

First congratulations for this repository, let me know to you that im begginer but I can donwload all the off grid version, unfortunable afer fill up the form I did on click in calculate , but nothing happend.
sorry for me english I am from argentina, Best  Regards.

let me know if I do well contact to you for this way, where can contact each one best, cheers!

**Comment by just-a-rookie-2001** [comment]
I have updated the README with all the instructions related to downloading this project. I would recommend that you download the entire repository instead of the "off-grid version" as it would be easy to debug.

- Make sure you have VSCode 'live server' extension or python HTTP server running
- Always click on the "Next" button to navigate to the next part. This saves the data you enter in the forms
- Feel free to modify the data in the data.json file. (README covers this process)

There are some issues related to the pricing and currency (currently INR{₹}) which will be fixed in the future commit.
